language: 
- python
- 3.4

script:
  - mkdir mydir
  - touch myfil
  - echo abc

before_deploy:
  echo "before deploy"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
after_deploy:
  echo "after deploy"
