language: 
- python
- 3.4

script:
  - mkdir mydir
  - touch myfil
  - echo abc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
